export const LOGIN_MODAL = "LOGIN_MODAL";
export const SHOW_MESSAGE_MODAL = "SHOW_MESSAGE_MODAL";
export const ADD_MESSAGE_MODAL = "ADD_MESSAGE_MODAL";
export const HIDE_MESSAGE_MODAL = "HIDE_MESSAGE_MODAL";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const REGISTER_USER = "REGISTER_USER";
